name: CI Pipeline - DEV
on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  deploy-dev:
    if: false
    uses: ./.github/workflows/ci-pipeline.yml
    with:
      git_branch          : 'dev'
      release_type        : 'minor'
      should_increment_tag: true
      artifact_retention_days: 7
    secrets: inherit
